[copy of] Tentative fixes for the atddiff check #207 (#211)
This is the same set of changes as #207 but I pushed this branch to the
original repo owned by semgrep instead of my personal fork. The CI
checks should now all pass.

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -31,7 +31,7 @@ jobs:
         set -x
 
         git config --global --add safe.directory "$(pwd)"
-        
+
         # github actions sets HOME=/home/github where we don't have an opam env
         eval $(HOME=/root opam env)
         apk add jq
@@ -40,9 +40,12 @@ jobs:
         atddiff --version
 
         # run the checks
-        echo -ne 'Backwards compatability summary:\n\n```' > summary-00-header.txt
+        echo -ne 'Backwards compatibility summary:\n\n```' > summary-00-header.txt
         echo '```' >> summary-20-footer.txt
-        ./scripts/check-backwards-compatability.sh | tee summary-10-body.txt
+
+        # fail if check command fails
+        set -o pipefail
+        ./scripts/check-backwards-compatibility | tee summary-10-body.txt
 
     - uses: marocchino/sticky-pull-request-comment@v2
       if: ${{ !cancelled() }}
