run all loops

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -26,11 +26,11 @@ jobs:
           opam-depext: false
           dune-cache: true
 
-      - run: opam install atd
+      - name: install atddiff
+        run: opam install atd
 
       - name: atddiff all supported tags
         run: |
-            set -e
             eval $(opam env)
 
             # fetch minimum version and enumerate tags for supported releases
@@ -39,6 +39,7 @@ jobs:
 
             # check tags
             checked=()
+            errors=0
             for tag in $tags; do
                 commit=$(git rev-list -n 1 "$tag")
                 if [[ "${checked[*]}" =~ $commit ]]; then
@@ -49,4 +50,13 @@ jobs:
 
                 echo "Checking backward compatibility of semgrep_output_v1.atd against past version $tag"
                 git difftool -x 'atddiff --backward' -y --trust-exit-code "$tag" semgrep_output_v1.atd
+
+                if [ $? -ne 0 ]; then
+                    echo "ERROR: semgrep_output_v1.atd is not backward compatible with $tag"
+                    errors=$((errors + 1))
+                fi
             done
+
+            if [ $errors -eq 0 ]; then
+                exit 1
+            fi
